### ISSUE TITLE
KeyError: "weight" in convert_ti_output_to_formatted.py

### ISSUE THREAD

**Issue by xgeric** [acocos/tax-org#1]
Hi Anne,

Thank you for the nice work! I am reading your paper and trying to execute your code. When executing run_experiments.sh I came across KeyError: "weight" in line 138 (newtaxo = util.nx2dct) of convert_ti_output_to_formatted.py.

My guess after some inspection is you missed the "weight" attribute at line 91 of convert_ti_output_to_formatted.py when adding new edges to the graph. I am wondering: what is the expected behavior here (i.e., what are the expected weights of added edges)? Could you please fix the error or kindly inform me of the expected behavior?

Thanks!

**Comment by acocos** [comment]
Thanks for letting me know about this error!

The weight attribute has no function within `convert_ti_output_to_formatted.py` -- it doesn't matter. This method is just converting the taxonomy output to a format for printing, and the weights are not printed. I updated util.nx2dct to set the 'relation' and 'weight' attributes to None if they are absent. Please let me know if you have any other issues.
